name: CI Simple
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Ejecutar script python
        run: |
          echo "print('Hola desde python!')" > script.py
          python3 script.py
